/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BadgeType = IDL.Variant({
  'streak' : IDL.Null,
  'quizMaster' : IDL.Null,
  'stageComplete' : IDL.Null,
  'levelComplete' : IDL.Null,
});
export const Badge = IDL.Record({
  'dateEarned' : IDL.Int,
  'badgeType' : BadgeType,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Certificate = IDL.Record({
  'dateEarned' : IDL.Int,
  'stage' : IDL.Text,
  'levelRange' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'xp' : IDL.Nat,
  'totalBadges' : IDL.Nat,
  'username' : IDL.Text,
  'coins' : IDL.Nat,
  'badges' : IDL.Vec(Badge),
  'streakDays' : IDL.Nat,
  'currentLevel' : IDL.Nat,
  'unlockedLevels' : IDL.Vec(IDL.Nat),
  'certificates' : IDL.Vec(Certificate),
  'lastActive' : IDL.Int,
  'completedLevels' : IDL.Vec(IDL.Nat),
  'avatar' : IDL.Nat,
});
export const QuestionType = IDL.Variant({
  'mcq' : IDL.Null,
  'outputPredict' : IDL.Null,
  'debugging' : IDL.Null,
  'fillBlank' : IDL.Null,
});
export const Question = IDL.Record({
  'explanation' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'questionText' : IDL.Text,
  'questionType' : QuestionType,
  'wrongExplanations' : IDL.Vec(IDL.Text),
  'options' : IDL.Vec(IDL.Text),
});
export const Level = IDL.Record({
  'concept' : IDL.Text,
  'miniQuiz' : IDL.Vec(Question),
  'title' : IDL.Text,
  'xpReward' : IDL.Nat,
  'practiceQuestions' : IDL.Vec(Question),
  'coinReward' : IDL.Nat,
  'levelNumber' : IDL.Nat,
  'stage' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardBadge' : IDL.Func([IDL.Principal, Badge], [], []),
  'checkDailyStreak' : IDL.Func([], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getLevel' : IDL.Func([IDL.Nat], [Level], ['query']),
  'getUserBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
  'getUserCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordCertificate' : IDL.Func([IDL.Principal, Certificate], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BadgeType = IDL.Variant({
    'streak' : IDL.Null,
    'quizMaster' : IDL.Null,
    'stageComplete' : IDL.Null,
    'levelComplete' : IDL.Null,
  });
  const Badge = IDL.Record({
    'dateEarned' : IDL.Int,
    'badgeType' : BadgeType,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Certificate = IDL.Record({
    'dateEarned' : IDL.Int,
    'stage' : IDL.Text,
    'levelRange' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'xp' : IDL.Nat,
    'totalBadges' : IDL.Nat,
    'username' : IDL.Text,
    'coins' : IDL.Nat,
    'badges' : IDL.Vec(Badge),
    'streakDays' : IDL.Nat,
    'currentLevel' : IDL.Nat,
    'unlockedLevels' : IDL.Vec(IDL.Nat),
    'certificates' : IDL.Vec(Certificate),
    'lastActive' : IDL.Int,
    'completedLevels' : IDL.Vec(IDL.Nat),
    'avatar' : IDL.Nat,
  });
  const QuestionType = IDL.Variant({
    'mcq' : IDL.Null,
    'outputPredict' : IDL.Null,
    'debugging' : IDL.Null,
    'fillBlank' : IDL.Null,
  });
  const Question = IDL.Record({
    'explanation' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'questionText' : IDL.Text,
    'questionType' : QuestionType,
    'wrongExplanations' : IDL.Vec(IDL.Text),
    'options' : IDL.Vec(IDL.Text),
  });
  const Level = IDL.Record({
    'concept' : IDL.Text,
    'miniQuiz' : IDL.Vec(Question),
    'title' : IDL.Text,
    'xpReward' : IDL.Nat,
    'practiceQuestions' : IDL.Vec(Question),
    'coinReward' : IDL.Nat,
    'levelNumber' : IDL.Nat,
    'stage' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardBadge' : IDL.Func([IDL.Principal, Badge], [], []),
    'checkDailyStreak' : IDL.Func([], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getLevel' : IDL.Func([IDL.Nat], [Level], ['query']),
    'getUserBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
    'getUserCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordCertificate' : IDL.Func([IDL.Principal, Certificate], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };