/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Badge {
  'dateEarned' : bigint,
  'badgeType' : BadgeType,
  'name' : string,
  'description' : string,
}
export type BadgeType = { 'streak' : null } |
  { 'quizMaster' : null } |
  { 'stageComplete' : null } |
  { 'levelComplete' : null };
export interface Certificate {
  'dateEarned' : bigint,
  'stage' : string,
  'levelRange' : string,
}
export interface Level {
  'concept' : string,
  'miniQuiz' : Array<Question>,
  'title' : string,
  'xpReward' : bigint,
  'practiceQuestions' : Array<Question>,
  'coinReward' : bigint,
  'levelNumber' : bigint,
  'stage' : string,
}
export interface Question {
  'explanation' : string,
  'correctAnswer' : string,
  'questionText' : string,
  'questionType' : QuestionType,
  'wrongExplanations' : Array<string>,
  'options' : Array<string>,
}
export type QuestionType = { 'mcq' : null } |
  { 'outputPredict' : null } |
  { 'debugging' : null } |
  { 'fillBlank' : null };
export interface UserProfile {
  'xp' : bigint,
  'totalBadges' : bigint,
  'username' : string,
  'coins' : bigint,
  'badges' : Array<Badge>,
  'streakDays' : bigint,
  'currentLevel' : bigint,
  'unlockedLevels' : Array<bigint>,
  'certificates' : Array<Certificate>,
  'lastActive' : bigint,
  'completedLevels' : Array<bigint>,
  'avatar' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardBadge' : ActorMethod<[Principal, Badge], undefined>,
  'checkDailyStreak' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getLevel' : ActorMethod<[bigint], Level>,
  'getUserBadges' : ActorMethod<[], Array<Badge>>,
  'getUserCertificates' : ActorMethod<[], Array<Certificate>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordCertificate' : ActorMethod<[Principal, Certificate], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];