/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Level {
    concept: string;
    miniQuiz: Array<Question>;
    title: string;
    xpReward: bigint;
    practiceQuestions: Array<Question>;
    coinReward: bigint;
    levelNumber: bigint;
    stage: string;
}
export interface Badge {
    dateEarned: bigint;
    badgeType: BadgeType;
    name: string;
    description: string;
}
export interface Question {
    explanation: string;
    correctAnswer: string;
    questionText: string;
    questionType: QuestionType;
    wrongExplanations: Array<string>;
    options: Array<string>;
}
export interface Certificate {
    dateEarned: bigint;
    stage: string;
    levelRange: string;
}
export interface UserProfile {
    xp: bigint;
    totalBadges: bigint;
    username: string;
    coins: bigint;
    badges: Array<Badge>;
    streakDays: bigint;
    currentLevel: bigint;
    unlockedLevels: Array<bigint>;
    certificates: Array<Certificate>;
    lastActive: bigint;
    completedLevels: Array<bigint>;
    avatar: bigint;
}
export enum BadgeType {
    streak = "streak",
    quizMaster = "quizMaster",
    stageComplete = "stageComplete",
    levelComplete = "levelComplete"
}
export enum QuestionType {
    mcq = "mcq",
    outputPredict = "outputPredict",
    debugging = "debugging",
    fillBlank = "fillBlank"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    awardBadge(user: Principal, badge: Badge): Promise<void>;
    checkDailyStreak(): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLeaderboard(): Promise<Array<[Principal, UserProfile]>>;
    getLevel(levelNumber: bigint): Promise<Level>;
    getUserBadges(): Promise<Array<Badge>>;
    getUserCertificates(): Promise<Array<Certificate>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    recordCertificate(user: Principal, certificate: Certificate): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateUserProfile(updatedProfile: UserProfile): Promise<void>;
}
import type { Badge as _Badge, BadgeType as _BadgeType, Certificate as _Certificate, Level as _Level, Question as _Question, QuestionType as _QuestionType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async awardBadge(arg0: Principal, arg1: Badge): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.awardBadge(arg0, to_candid_Badge_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardBadge(arg0, to_candid_Badge_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkDailyStreak(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.checkDailyStreak();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkDailyStreak();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLevel(arg0: bigint): Promise<Level> {
        if (this.processError) {
            try {
                const result = await this.actor.getLevel(arg0);
                return from_candid_Level_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLevel(arg0);
            return from_candid_Level_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserBadges(): Promise<Array<Badge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBadges();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBadges();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserCertificates(): Promise<Array<Certificate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCertificates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCertificates();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordCertificate(arg0: Principal, arg1: Certificate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordCertificate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordCertificate(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(to_candid_UserProfile_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(to_candid_UserProfile_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BadgeType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BadgeType): BadgeType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Badge_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Badge): Badge {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Level_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Level): Level {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionType): QuestionType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateEarned: bigint;
    badgeType: _BadgeType;
    name: string;
    description: string;
}): {
    dateEarned: bigint;
    badgeType: BadgeType;
    name: string;
    description: string;
} {
    return {
        dateEarned: value.dateEarned,
        badgeType: from_candid_BadgeType_n13(_uploadFile, _downloadFile, value.badgeType),
        name: value.name,
        description: value.description
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    concept: string;
    miniQuiz: Array<_Question>;
    title: string;
    xpReward: bigint;
    practiceQuestions: Array<_Question>;
    coinReward: bigint;
    levelNumber: bigint;
    stage: string;
}): {
    concept: string;
    miniQuiz: Array<Question>;
    title: string;
    xpReward: bigint;
    practiceQuestions: Array<Question>;
    coinReward: bigint;
    levelNumber: bigint;
    stage: string;
} {
    return {
        concept: value.concept,
        miniQuiz: from_candid_vec_n21(_uploadFile, _downloadFile, value.miniQuiz),
        title: value.title,
        xpReward: value.xpReward,
        practiceQuestions: from_candid_vec_n21(_uploadFile, _downloadFile, value.practiceQuestions),
        coinReward: value.coinReward,
        levelNumber: value.levelNumber,
        stage: value.stage
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    explanation: string;
    correctAnswer: string;
    questionText: string;
    questionType: _QuestionType;
    wrongExplanations: Array<string>;
    options: Array<string>;
}): {
    explanation: string;
    correctAnswer: string;
    questionText: string;
    questionType: QuestionType;
    wrongExplanations: Array<string>;
    options: Array<string>;
} {
    return {
        explanation: value.explanation,
        correctAnswer: value.correctAnswer,
        questionText: value.questionText,
        questionType: from_candid_QuestionType_n24(_uploadFile, _downloadFile, value.questionType),
        wrongExplanations: value.wrongExplanations,
        options: value.options
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    totalBadges: bigint;
    username: string;
    coins: bigint;
    badges: Array<_Badge>;
    streakDays: bigint;
    currentLevel: bigint;
    unlockedLevels: Array<bigint>;
    certificates: Array<_Certificate>;
    lastActive: bigint;
    completedLevels: Array<bigint>;
    avatar: bigint;
}): {
    xp: bigint;
    totalBadges: bigint;
    username: string;
    coins: bigint;
    badges: Array<Badge>;
    streakDays: bigint;
    currentLevel: bigint;
    unlockedLevels: Array<bigint>;
    certificates: Array<Certificate>;
    lastActive: bigint;
    completedLevels: Array<bigint>;
    avatar: bigint;
} {
    return {
        xp: value.xp,
        totalBadges: value.totalBadges,
        username: value.username,
        coins: value.coins,
        badges: from_candid_vec_n10(_uploadFile, _downloadFile, value.badges),
        streakDays: value.streakDays,
        currentLevel: value.currentLevel,
        unlockedLevels: value.unlockedLevels,
        certificates: value.certificates,
        lastActive: value.lastActive,
        completedLevels: value.completedLevels,
        avatar: value.avatar
    };
}
function from_candid_tuple_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n8(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    streak: null;
} | {
    quizMaster: null;
} | {
    stageComplete: null;
} | {
    levelComplete: null;
}): BadgeType {
    return "streak" in value ? BadgeType.streak : "quizMaster" in value ? BadgeType.quizMaster : "stageComplete" in value ? BadgeType.stageComplete : "levelComplete" in value ? BadgeType.levelComplete : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mcq: null;
} | {
    outputPredict: null;
} | {
    debugging: null;
} | {
    fillBlank: null;
}): QuestionType {
    return "mcq" in value ? QuestionType.mcq : "outputPredict" in value ? QuestionType.outputPredict : "debugging" in value ? QuestionType.debugging : "fillBlank" in value ? QuestionType.fillBlank : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Badge>): Array<Badge> {
    return value.map((x)=>from_candid_Badge_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n22(_uploadFile, _downloadFile, x));
}
function to_candid_BadgeType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BadgeType): _BadgeType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Badge_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Badge): _Badge {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    totalBadges: bigint;
    username: string;
    coins: bigint;
    badges: Array<Badge>;
    streakDays: bigint;
    currentLevel: bigint;
    unlockedLevels: Array<bigint>;
    certificates: Array<Certificate>;
    lastActive: bigint;
    completedLevels: Array<bigint>;
    avatar: bigint;
}): {
    xp: bigint;
    totalBadges: bigint;
    username: string;
    coins: bigint;
    badges: Array<_Badge>;
    streakDays: bigint;
    currentLevel: bigint;
    unlockedLevels: Array<bigint>;
    certificates: Array<_Certificate>;
    lastActive: bigint;
    completedLevels: Array<bigint>;
    avatar: bigint;
} {
    return {
        xp: value.xp,
        totalBadges: value.totalBadges,
        username: value.username,
        coins: value.coins,
        badges: to_candid_vec_n28(_uploadFile, _downloadFile, value.badges),
        streakDays: value.streakDays,
        currentLevel: value.currentLevel,
        unlockedLevels: value.unlockedLevels,
        certificates: value.certificates,
        lastActive: value.lastActive,
        completedLevels: value.completedLevels,
        avatar: value.avatar
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateEarned: bigint;
    badgeType: BadgeType;
    name: string;
    description: string;
}): {
    dateEarned: bigint;
    badgeType: _BadgeType;
    name: string;
    description: string;
} {
    return {
        dateEarned: value.dateEarned,
        badgeType: to_candid_BadgeType_n5(_uploadFile, _downloadFile, value.badgeType),
        name: value.name,
        description: value.description
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BadgeType): {
    streak: null;
} | {
    quizMaster: null;
} | {
    stageComplete: null;
} | {
    levelComplete: null;
} {
    return value == BadgeType.streak ? {
        streak: null
    } : value == BadgeType.quizMaster ? {
        quizMaster: null
    } : value == BadgeType.stageComplete ? {
        stageComplete: null
    } : value == BadgeType.levelComplete ? {
        levelComplete: null
    } : value;
}
function to_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Badge>): Array<_Badge> {
    return value.map((x)=>to_candid_Badge_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
